### ISSUE TITLE
Wrong TextLabel parameter for latest Streamer release

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#193]
Compiler errors:
```
sss/core/admin/name-tags.pwn(53) : error 035: argument type mismatch (argument 14)
sss/core/admin/name-tags.pwn(54) : error 035: argument type mismatch (argument 14)
```

Respective lines from `name-tags.pwn`
```
tags_Nametag[playerid] = CreateDynamic3DTextLabelEx(exampletext, YELLOW, 0.0, 0.0, 0.0, 6000.0, playerid, _, 0, 6000.0, _, _, players, 1, 1, maxplayers);
tags_NametagLOS[playerid] = CreateDynamic3DTextLabelEx(exampletext, BLUE, 0.0, 0.0, 0.0, 6000.0, playerid, _, 1, 6000.0, _, _, players, 1, 1, maxplayers);
```

This is using the latest streamer from Incognito, which is [2.8](https://github.com/samp-incognito/samp-streamer-plugin/releases/tag/v2.8)

This doesn't occur with the [2.7.9](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.7.9/streamer-plugin-2.7.9.zip) release which is how SS is currently built on.

The references in the main file should be updated with the right versions. Because for example, the streamer reference only points to 2.7 instead of 2.7.9.

**Comment by Southclaw** [comment]
Ah good catch, I've not needed to upgrade the streamer as that version works fine and I've seen quite a few people complaining about issues with the newer versions.

My current version is v2.7.5.2 so I'll write that for now and when I get the test server open I'll experiment with later versions. If there are any bugs you know about that specifically happen in SS due to that streamer version let me know and I'll upgrade to the next version.

**Comment by viruxe** [comment]
Well for now 2.7.9 is working fine. But yes you should specify that you are using 2.7.5
