### ISSUE TITLE
Campfire mechanics

### ISSUE THREAD

**Issue by viruxe** [Southclaw/ScavengeSurvive#223]
I have a feeling I have already brought this up for discussion somewhere. But anyway...

Right now it is very difficult to craft a campfire. You need to get two boxes into a trunk in order to successfully combine the two into a campfire.

Perhaps we could just simply setup a mechanism where a player hammers a box for it to yeild a campfire - almost like the mechanism for the tents.

**Comment by Southclaw** [comment]
I'll be switching to wood soon due to the tree system.

The hammer thing wouldn't work, what if you simply wanted to put a hammer into a box?

**Comment by viruxe** [comment]
While holding a hammer and holding the action key on top of a box the char would hammer it to make wood. And pressing the action key would open it.

**Comment by Southclaw** [comment]
Now that trees have been added, logs can be combined to create a campfire (3 to be exact, two on the floor and one in hand, hold F at the 2 on the floor to combine into a campfire).

However, I still think it may be a bit "hard" to make a campfire since to get logs from a tree, a chainsaw with fuel is required! (I replaced the problem with another problem).

I will probably add logs to industrial vehicle spawns so trucks spawn with logs in sometimes but I don't want to make tree-chopping useless by making logs too common so it's still a problem.

Using a hammer with a safebox would require lots of fucking around with the safebox trigger code (it's coded so hitting F near *any* safeboxes opens them, whether or not you hold the key or tap it with an item in hand).

So I was thinking of making the Crowbar item a "universal" destruction item for destroying items. How this would work is not with the F key but with the LMB (fire) key to destroy various types of items and turn them into their ingredients or another item (so Crowbarring a box turns it into wood logs, etc) similar to how the Scrap Machine can be used to de-construct metal items into scrap metal.

Obviously it's another mechanic that's going to be new to players (old and new) so I'm still skeptical. Also, base raids could turn into hilarious destructive rampages if raiders won't bother to check every box, they could just destroy all the boxes (resulting in the items appearing in the world).

Anyway, would love to have some input on this!

**Comment by Southclaw** [comment]
![https://dl.dropboxusercontent.com/u/45512231/ShareX/2016-05-22_11-23-46.gif](https://dl.dropboxusercontent.com/u/45512231/ShareX/2016-05-22_11-23-46.gif)

**Comment by Southclaw** [comment]
Oh fuck, it works! Never mind...

![https://dl.dropboxusercontent.com/u/45512231/ShareX/2016-05-22_11-44-27.gif](https://dl.dropboxusercontent.com/u/45512231/ShareX/2016-05-22_11-44-27.gif)

**Comment by Southclaw** [comment]
Fixed in c5205545ef88b1b47b184df80e8b8a0c6a011454
