### ISSUE TITLE
Reason doesn't shows up in

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#256]
[18:24:32] [ADDITEM] Renga added item AdvancedKeypad (d:179) reason: 
On /additem item never asks for an reason 
https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/sss/core/admin/level3.pwn#L452
Line 452

**Comment by kadaradam** [comment]
It does work, the admin just did not type any reason in the input field. You should seriously stop opening these useless issues. If you don't know the basics of scripting you should not have a server.

I don't even know why you care about adding reason to /additem, since all items on your server are abused.

**Comment by Southclaw** [comment]
[Did you actually read the code?](https://github.com/Southclaw/ScavengeSurvive/blob/master/gamemodes/sss/core/admin/level3.pwn#L536-L545)

I was going to say it was related to #248 but that's impossible. The log you posted is executed on an inline dialog callback so the user must have responded to the dialog.

I'd worry less about code right now and more about your admins abusing their powers. There should *never* be any reason for items to be spawned in apart from in the case of a glitch or hacker. When I owned a server I NEVER let any of my staff members spawn in anything, I would personally oversee *every single case* where anything would require to be spawned since I took admin abuse very seriously and cared about ally my players having a fair game.
