### ISSUE TITLE
[SetItemArrayData] data length 1 exceeds item type data size of 0.

### ISSUE THREAD

**Issue by XFlawless1** [Southclaw/ScavengeSurvive#263]
> [01:42:28] ERROR: [SetItemArrayData] data length 1 exceeds item type data size of 0.

Until my admins doesn't restarts the servers x2 from panel.
My players cannot login.

**Comment by Southclaw** [comment]
When does this happen? Which itemtype is this for?

**Comment by trojan-sas** [comment]
i don't think the two problems connected to each other as [01:42:28] ERROR: [SetItemArrayData] data length 1 exceeds item type data size of 0. is not related to the players kick out actually idk  for which item the first error but for the sec issue its just happen when the server restart however the restart is manual or auto restart it just kick out players whenever they try to login the fix is so annoying as u need to restart the server "twice" to make it works.
LOGS: 
[19:48:01] [LOAD] Snakai (account exists, prompting login) Alive: 1 Last login: Sunday Jun 26 2016 at 19:38:27
[19:48:01] [LOGPROMPT] Snakai is logging in
[19:48:39] [connection] 156.204.5.4:14177 requests connection cookie.
[19:49:10] Kicking 156.204.5.4 because they didn't logon to the game.
[19:49:33] [connection] 156.204.5.4:14212 requests connection cookie.
[19:49:48] [connection] 31.210.187.159:43768 requests connection cookie.
[19:50:09] [connection] 156.204.5.4:14232 requests connection cookie.
[19:50:19] Kicking 31.210.187.159 because they didn't logon to the game.
[19:50:40] Kicking 156.204.5.4 because they didn't logon to the game.
as well as i have a theory that this issue is connected to an earlier issue: https://github.com/Southclaw/ScavengeSurvive/issues/248

**Comment by XFlawless1** [comment]
@trojan-sas 
The above you said was already stated by @Southclaw 
That is due to [LOADACCOUNTDELAY]
Something's wrong with it,
It's very wrongly set or is an wrong integer.
Thats how players can't login.

**Comment by Southclaw** [comment]
What do you mean by wrongly set? The delay?

All that does is make the database calls deferred slightly from the initial connection database stuff in order to prevent long thread hangs.

If there's actually a server hang or login issue, open another issue for it.

**Comment by XFlawless1** [comment]
It was already opened up by @karadaram

**Comment by Southclaw** [comment]
I don't think `Kicking 156.204.5.4 because they didn't logon to the game` is related to #248 as that's related to dialogs. That particular error message looks more like a full server freeze rather than just the YSI dialog issue (where the server is still running fine, it's just dialogs that fail).

**Comment by XFlawless1** [comment]
But i don't think its always a 

> dialog 

problem
Every restart leads the players to kick.

**Comment by kadaradam** [comment]
wow, bunch of smartasses

**Comment by Southclaw** [comment]
Like I've said many times before, one topic per issue.

If there's a problem causing the server to hang, open another issue for it.

I'll add itemtypes to these error messages so you can report the itemtype that needs adjusting.
