### ISSUE TITLE
Skills/Experience

### ISSUE THREAD

**Issue by Southclaw** [Southclaw/ScavengeSurvive#303]
Skills will be a stat that affects the speed at which certain actions take to complete.

Actions affected by skill values:
- [x] - Construction of Defences
- [x] - Construction of each `craft-construct` recipe
- [x] - Crafting of each `workbench` recipe
- [x] - Vehicle repair
- [x] - Medical Item Usage
- [x] - Forestry
- [x] - Fishing
- [ ] - Running (some form of "endurance" based on time spent running)

Notes:
Each recipe will have its own skill level so a player could become a master at just crafting timed TNT explosives.

Experience will be a floating point number with a default value of `0.01` which will be used in a function to calculate a value to subtract from the `time` parameter in `StartHoldAction` calls. Higher values will result in shorter `time` values and faster completion of actions. The maximum value (skill-cap) for this will be `2.0` which would cut action times in half.

Representing experience to players will not be in the form of a floating point value to keep things simple. The representation to players will be in the form of colours and skill names:
- Novice, Yellow
- Adequate, Green
- Intermediate, Orange
- Experienced, Blue
- Master, Purple

Gaining experience will follow this graph:

![image](https://cloud.githubusercontent.com/assets/1636971/17839166/2892cde0-67d8-11e6-92ba-71f584ef8443.png)

Where the X axis represents the player's current experience with a skill value (1.0 - 2.0) and the Y axis represents the experience gained from performing an action of the skill (0.01 - 1.0)

This means that new players gain experience slowly through "Novice" and "Adequate" but will pick up the pace after a while and will travel through "Intermediate" faster then experience gain will slow down as they near the "Experienced" and "Master" levels. This can be tweaked based on player feedback and engagement with the system. (The S-Curve model is derived from various mobile game reward-rate research)

Formulae:
- Experience gain:
  `0.1 * ((3 * pow(exp, 2) - 2 * pow(exp, 3)))` with range 0.01..1.0
- `StartHoldAction` Time subtraction:
  `time - round(pow(exp * 100, 2))`

With these values, it would take a total of 347 actions to reach the skill cap.

**Comment by Patrik356b** [comment]
that's a pretty awful image, otherwise it's a very interesting concept

**Comment by trojan-sas** [comment]
its the one last thing that sas needs... but it should go wilder than just fast repairing etc. it should also be with a score system like when u get score ur exp increase and when u reach lvl one u get a skill you can consider add alot of skill for example: mechanic(can build faster and repair faster),healer(so u can use a command give u like 15%of ur health),stamina(endurance) so u get less hungry,hitman(so your aim skill become more better),
so here is how it should work like ..when u kill someone or when you stay for like 15 min or something u get score and when u reach specific no. of score you get the first skill level and so on 
i see that it gonna take time but in my opinion it deserve  
one other idea is about adding a rare craftable item that make u set a spawn position and it use for one time idk if that possible but its a good idea especially when u get killed its worthless to walk to the other cities to reach ur destination

**Comment by Southclaw** [comment]
It is effectively a "score system" already. I will probably add medical actions to the list too. One thing I am staying away from though is combat, combat should stay fair and not be affected by magical imaginary numbers - just players with their guns and physical mouse skill, nothing else.

I may consider endurance or something similar to keep players active on the server (possibly running speed if I can alter it effectively). I don't really want to turn the game into too much of an arcade shooter so I won't be adding publicised "scores", when two players encounter one another there should be little information as to how the encounter may go down and players should be able to lie about their skills (and just about anything really).

**Comment by Patrik356b** [comment]
You could perhaps make use of a health/armor cap. Another idea which might be worth looking into is the use of SetPlayerGravity but it requires a plug-in

**Comment by Southclaw** [comment]
I may think about health, armour is a no go since that's a physical item out of the player's control (armour strength is controlled by the state of the item, not the state of the player).

As for player health, I may do something related to this as "what don't kill you makes you stronger" so maybe wound healing could act as an "action" to trigger "expperience" gain (whereas instead of representing experience, it's representing the body's physical strength).

Factors that affect player's "health" are:
- Blood regeneration speed (currently only affected by hunger level - low hunger = faster regen)
- Blood loss rate - all that affects this is the weapon that made the wound
- Wound knockout chance - currently affected by adrenaline to guarantee consciousness

As for agility, I could use SetPlayerVelocity to increase jump height/distance a bit - I'd actually love to add some areas that can only be accessed via jumping with this so players must get their agility experience up before being able to access these areas. Either way, I want to avoid the SetPlayerGravity as that plugin isn't maintained and I've heard of quite a few compatibility issues!

**Comment by trojan-sas** [comment]
hhm but the 1st thing i like in this gamemode is 1 shoot 1 kill don't you think?

**Comment by Southclaw** [comment]
I've never been a fan of one-shot-kill mechanics, it doesn't really garner gunplay skill or combat manoeuvres - it bases fights purely on a "who sees who first" basis which is why it's never been a true mechanic in the game.

Of course one-shot scenarios still exist but they are "one-shot-down" rather than "kill" and they only occur with the correct circumstances (a very high weapon calibre or the shot distance is low or the victim is already wounded).

**Comment by Southclaw** [comment]
Updated the formulae:
- Gaining skill experience: `0.001 + 0.001 * ((3 * pow(exp, 2) - 2 * pow(exp, 3)))`
- `StartHoldAction` subtraction: `round(time - time * (0.5 * exp))` where `time` is the max time
This means the maximum speed increase on all skills is 50% and skill values don't need to be initialised at 0.001.

**Comment by Southclaw** [comment]
Currently implementing in `skills` branch.

**Comment by Southclaw** [comment]
Currently implementing in `skills` branch: https://github.com/Southclaw/ScavengeSurvive/tree/skills

**Comment by Southclaw** [comment]
Current todo:
- [ ] make a menu to present skills to the player
- [ ] figure out a way to present/name crafting skills (currently uses the craftset hash)
- [ ] figure out a way to make the current system work for an agility/stamina modifier

**Comment by Southclaw** [comment]
Added Forestry and Fishing to the list of actions that need skills.

**Comment by FelipeeBR** [comment]
Class system

Commands to upgrade fight or color class:
/ Update class
/ Refreshclass
__________________________________________________ ________________________________________
0 - 20 scores:
Class: Civil.
Color white.
Description: You are a citizen who has started now and has not yet come to fight for your survival and has no experience yet that will give you advantages over other players.
__________________________________________________ ________________________________________
20 - 50 score:
Class: Survivor.
Yellow color.
Description: You fought for your survival and had to decide between life or death and with that you gained fighting ability, you can also wear the survivor clothing.
Fighting Style: Boxing.

Commands:

/ Classemale - This command is used to wear the male clothes of the surviving class.
/ Classefemale - This command is used to wear the surviving class women's clothing.
__________________________________________________ ________________________________________
50 - 100 scores:
Class: Bandit.
Purple color.
Description: You have been killing many people and this has left you with a bad reputation, no one else trusts you because you have not followed the survival instinct. The tendency is to have the dirtiest reputation over time, because without trust will force you to kill more people even if you wish not to kill them.
Fight style: Street fighting.

Commands:

/ Classemale - This command is used to wear the male clothes of the surviving class.
/ Classefemale - This command is used to wear the surviving class women's clothing.
__________________________________________________ ________________________________________
100 - 200 scores:
Class: Assassin.
Red color.
Description: You have walked a totally different path to survival, your blood pleasure has increased even more and your pleasure is to see dead people and this will leave you even more with the low reputation among the survivors but between your means will be with high reputation and Respect putting fear in anyone who enters into combat with you.
Fight style: Kung fu.

Commands:

/ Classemale - This command is used to wear the male clothes of the surviving class.
/ Classefemale - This command is used to wear the surviving class women's clothing.
/ Skilleclasse - Uses ability with class weapons (Pistols).
/ Hiddermochila - Hide the backpack so nobody can see from afar
__________________________________________________ ________________________________________
200 - 300 scores:
Class: Terrorist.
Green color.
Description: You are a professional when it comes to fighting one or more people, your reputation is high among your means, even groups of bad guys will have to face you. Surely you did not reach this class by chance, you were not born to be the good guy.
Fight style: Kung fu.

Commands:

/ Classemale - This command is used to wear the male clothes of the surviving class.
/ Classefemale - This command is used to wear the surviving class women's clothing.
/ Skilleclasse - Uses ability with class weapons (Pistols and Sawn-off).
/ Hiddermochila - Hide the backpack so nobody can see from afar
__________________________________________________ ________________________________________
300 - 400 score:
Class: Manic.
Color: Brown.
Description: You have totally lost your sanity, you no longer seek survival or take pleasure in killing other inferior people, but you can kill even the members of your group to quench your thirst for blood. But on the other hand you have gained a lot of experience on all your days and this has made you much more agile in combat, almost always guaranteeing your victory.
Fight style: Kung fu.

Commands:

/ Classemale - This command is used to wear the male clothes of the surviving class.
/ Classefemale - This command is used to wear the surviving class women's clothing.
/ Skilleclasse - Uses ability with class weapons (Pistols and Sawn-off).
/ Hiddermochila - Hide the backpack so nobody can see from afar
__________________________________________________ ________________________________________
400 - 500 scores:
Class: Psychopath.
Gray color.
Description: You are one step away from entering the most hated and most feared class of all, you are very strong almost nobody can face you without fear, of course this does not guarantee your victory but your experience gives you advantages over Remaining inferior and survivors.
Fight style: Kung fu.

Commands:

/ Classemale - This command is used to wear the male clothes of the surviving class.
/ Classefemale - This command is used to wear the surviving class women's clothing.
/ Skilleclasse - Uses ability with class weapons (Pistols and Sawn-off).
/ Hiddermochila - Hide the backpack so nobody can see from afar
